apiVersion: image.toolkit.fluxcd.io/v1beta3
kind: ImageRepository
metadata:
  name: imagerepository-sample
  namespace: flux-system
spec:
  image: ghcr.io/stefanprodan/podinfo
  interval: 1m0s
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
